### ISSUE TITLE
Game Saving / Loading

### ISSUE THREAD

**Issue by Daskie** [Daskie/Geocracy#49]

**Comment by andrewexton373** [comment]
i just merged to master what I was working on, it's all in a completed state as far as utility goes.. if we can remove all circular dependencies and strip the game object to include world and the players array, and just timestamps, current player. and remove any circular dependencies or anything that can be calculated during runtime by marking them as transient, we should be in a pretty good state to get full game saves to work. Currently got it working with the players array and some of their embedded objects such as territories.
